confidence_threshold: 0.4
frame_width: 640
frame_height: 480
frame_skip: 2
# COCO class IDs: car=2, motorcycle=3, bus=5, truck=7
allowed_classes:
  - 2
  - 3
  - 5
  - 7
class_names:
  2: car
  3: motorcycle
  5: bus
  7: truck
